### ISSUE TITLE
Docker failed to install

### ISSUE THREAD

**Issue by ibuildthecloud** [rancherio/10acre-ranch#2]
I got an error in which get.docker.io was not available.  I suspect that networking wasn't fully up at the time.  Maybe it would be good to add `--retry 5 --retry-delay 2` to the curl command.

**Comment by deniseschannon** [comment]
As of now, I haven't seen this issue being reproduced when running the script. I'm going to close this issue and if we start seeing it, we'll open a new issue in rancherio/rancher.
