### ISSUE TITLE
Can not add to PATH

### ISSUE THREAD

**Issue by ibuildthecloud** [rancherio/10acre-ranch#9]
The following line makes it so that you can't add this script to your path: https://github.com/cloudnautique/10acre-ranch/blob/7220d9812f44c92af30163a5b70d9c0243e0aa64/gce-10acre-ranch#L12

I don't have a great solution for this.  One hack could be to try `$(dirname $0)` and then try `$(dirname $(which $0))`.  I'm sure if you google around you'll find some fabulously complex approach to looking up the path of the current script in a consistent fashion.

**Comment by cloudnautique** [comment]
@ibuildthecloud I restructured the script a bit. Should make it easier to add to path now. I made the second script an actual script. Give it a spin, let me know what you think.
